#!/usr/bin/env python3
"""Generate mobileworld_splits.yaml — task-disjoint T_adapt / T_eval over the
161 GUI-only MobileWorld tasks, for cross-benchmark TTA (train AW+, eval MW).

Rules (deterministic, reproducible — no RNG, sorted by class name):
  - GUI-only = task_tags has no 'agent-mcp' (161 of 201).
  - eval tier per task: by Play-category membership of its apps
      Tier-B = all apps' category seen; Tier-C = all novel; Tier-A = mixed.
  - Tier-A (all multi-app, seen+novel) -> ALL eval  (compositional headline).
  - Tier-B / Tier-C -> split ~40% adapt, stratified by app-combo (frozenset
    of the task's apps); within each stratum sort by class name and take the
    first round(0.4*n) as adapt, rest eval. Task-disjoint by construction.
  - Adapt is the TTA fitness set (rolled out K x ~N_iters); eval is frozen.

Run:  python EvoFSM-MW/configs/gen_mobileworld_splits.py
"""
from __future__ import annotations
import ast, glob, collections, os

DEF = "MobileWorld/src/mobile_world/tasks/definitions"
OUT = "EvoFSM-MW/configs/mobileworld_splits.yaml"
ADAPT_FRAC = 0.40

CAT = {"Mail":"Communication","Messages":"Communication","Contacts":"Communication","Chrome":"Communication",
 "Calendar":"Productivity","Files":"Tools","Settings":"Tools","Clock":"Tools","Maps":"Maps & Navigation",
 "Gallery":"Photography","Camera":"Photography","Docreader":"Books & Reference",
 "Mastodon":"Social","Mattermost":"Social","Taodian":"Shopping"}
NOVEL = {"Social","Shopping"}

def setlit(n):
    if isinstance(n, ast.Set): return {ast.literal_eval(e) for e in n.elts if isinstance(e, ast.Constant)}
    try:
        v = ast.literal_eval(n); return set(v) if isinstance(v,(set,list,tuple)) else set()
    except Exception: return set()

def collect():
    out = []
    for f in sorted(glob.glob(f"{DEF}/**/*.py", recursive=True)):
        if f.endswith("__init__.py"): continue
        try: tree = ast.parse(open(f).read())
        except Exception: continue
        for nd in ast.walk(tree):
            if isinstance(nd, ast.ClassDef):
                apps = tags = None
                for b in nd.body:
                    if isinstance(b, ast.Assign):
                        for t in b.targets:
                            if isinstance(t, ast.Name) and t.id == "app_names": apps = setlit(b.value)
                            if isinstance(t, ast.Name) and t.id == "task_tags": tags = setlit(b.value)
                if apps and "agent-mcp" not in (tags or set()):
                    out.append((nd.name, tuple(sorted(apps)), os.path.relpath(f)))
    return out

def tier(apps):
    cats = {CAT.get(a, "?") for a in apps}
    s = any(c not in NOVEL for c in cats); n = any(c in NOVEL for c in cats)
    return "A" if (s and n) else ("C" if n else "B")

def main():
    tasks = collect()
    # de-dup by class name (keep first)
    seen=set(); uniq=[]
    for name,apps,path in tasks:
        if name in seen: continue
        seen.add(name); uniq.append((name,apps,path))
    tasks = uniq

    assign = {}  # class -> "adapt"|"eval"
    strata = collections.defaultdict(list)  # (tier, app-combo) -> [class]
    for name, apps, path in tasks:
        t = tier(apps)
        if t == "A":
            assign[name] = "eval"
        else:
            strata[(t, apps)].append(name)
    for (t, apps), names in strata.items():
        names_sorted = sorted(names)
        k = round(ADAPT_FRAC * len(names_sorted))
        for i, nm in enumerate(names_sorted):
            assign[nm] = "adapt" if i < k else "eval"

    # build records
    recs = []
    for name, apps, path in tasks:
        recs.append((name, list(apps), tier(apps), assign[name], path))
    recs.sort(key=lambda r: (r[2], r[3], r[0]))

    # emit yaml (hand-written for control)
    lines = []
    lines.append("# MobileWorld cross-benchmark TTA split (T_adapt / T_eval)")
    lines.append("# Generated by EvoFSM-MW/configs/gen_mobileworld_splits.py — do not hand-edit.")
    lines.append("# train domain = AndroidWorld+ 193 (source for pi^pre + static L_C).")
    lines.append("# test domain  = MobileWorld 161 GUI-only; split task-disjoint here.")
    lines.append("# Tier by Play-category membership (see docs/mobileworld_split.md).")
    lines.append("meta:")
    lines.append('  version: "v1.0-MW"')
    lines.append(f"  adapt_fraction: {ADAPT_FRAC}")
    lines.append("  rule: \"Tier-A all eval; Tier-B/C stratified by app-combo, round(40%) adapt, sorted by class name\"")
    n_ad = sum(1 for r in recs if r[3]=="adapt"); n_ev = len(recs)-n_ad
    lines.append(f"  totals: {{tasks: {len(recs)}, adapt: {n_ad}, eval: {n_ev}}}")
    by = collections.Counter((r[2], r[3]) for r in recs)
    lines.append("  per_tier:")
    for t in ["B","C","A"]:
        lines.append(f"    {t}: {{adapt: {by[(t,'adapt')]}, eval: {by[(t,'eval')]}}}")
    for split in ("adapt","eval"):
        lines.append(f"{split}:")
        for t in ["B","C","A"]:
            grp=[r for r in recs if r[2]==t and r[3]==split]
            if not grp: continue
            lines.append(f"  # Tier-{t} ({len(grp)})")
            for name, apps, tt, sp, path in grp:
                lines.append(f"  - {{task: {name}, tier: {t}, apps: {apps}}}")
    open(OUT,"w").write("\n".join(lines)+"\n")

    # summary to stdout
    print(f"wrote {OUT}: {len(recs)} tasks  adapt={n_ad}  eval={n_ev}")
    for t in ["B","C","A"]:
        print(f"  Tier-{t}: adapt={by[(t,'adapt')]:3d}  eval={by[(t,'eval')]:3d}")
    # per-app adapt coverage
    app_ad=collections.Counter(); app_ev=collections.Counter()
    for name, apps, t, sp, path in recs:
        for a in apps: (app_ad if sp=="adapt" else app_ev)[a]+=1
    print("\nper-app adapt / eval participation:")
    for a in sorted(set(app_ad)|set(app_ev), key=lambda a:(CAT.get(a,'?'),a)):
        print(f"  {CAT.get(a,'?'):18s} {a:10s} adapt={app_ad[a]:2d} eval={app_ev[a]:2d}")

if __name__ == "__main__":
    main()
